[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
  targetPort = 3000
  command = "npm run dev"
